apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: niximgs
build:
  artifacts:
    - custom:
        buildCommand:
          nix run github:shikanime-studio/nix-containers/d02b45cfaad223c5e6af7c7ff4b892e9ea707fe8 -- skaffold build
      image: ghcr.io/shikanime-labs/machines/catbox
