{
  modulesPath,
  pkgs,
  ...
}: {
  # Inherit base configuration from the flake.
  imports = [
    inputs.nixosModules.disko
    inputs.nixosModules.nix
    inputs.nixosModules.nixos
    inputs.nixosModules.extraSpecialArgs
    inputs.nixosModules.openssh
    inputs.nixosModules.sops
  ];

  # DO NOT EDIT — Machine type support. Defines flake outputs and NixOS module selection.
  sops = {
    age = {
      generateKey = true;
      keyFile = "/var/lib/sops-nix/key.txt";
    };
    defaultSopsFile = ../../secrets/catbox.enc.yaml;
    defaultSopsFormat = "yaml";
  };

  containerdisk = {
    name = "ghcr.io/shikanime-labs/machines/catbox";
    settings.LABELS = {
      "org.hermes.machines/vm" = "true";
    };

    settings.CONFIG = {
      # Configure kernel modules to load for VMs.
      kernelModules = [
        "virtio_pci"
        "virtio_net"
        "virtio_balloon"
        "virtio_blk"
        "virtio_rng"
        "virtio_console"
        "kvm"
        "kvm_intel"
        "vhost_net"
      ];

      # Configure kernel modules to load for VMs with GPU.
      kernelModulesGPU = [
        "virtio_pci"
        "virtio_net"
        "virtio_balloon"
        "virtio_blk"
        "virtio_rng"
        "virtio_console"
        "kvm"
        "kvm_intel"
        "vhost_net"
        "nvidia"
        "nvidia_uvm"
        "nvidia_drm"
        "nvidia_modeset"
      ];

      # Configure kernel modules to NOT load for VMs with GPU.
      kernelModulesGPUExclude = [
        "nouveau"
        "rivafb"
        "nvidiafb"
        "uvm"
        "drm"
        "nouveau"
      ];

      # Grow rootfs automatically on boot for KubeVirt PVCs.
      disk = {
        label = "rootfs";
        size = 4096;
        sizeUnit = "MiB";
      };

      partitions = {
        # Re-label the SOPS-encrypted disk to "data" for disk encryption.
        data = {
          label = "data";
          size = 512;
          sizeUnit = "MiB";
        };
      };

      # Configure fonts, kernel modules, and NTP for VMs.
      users = {
        admin = {
          name = "admin";
          passwordFile = "/dev/null";
          createHome = true;
          extraGroups = [
            "docker"
            "sudo"
            "input"
            "disk"
            "kvm"
            "render"
          ];
        };
      };

      systemd.services = {
        # Reseed the kernel randomness pool early in the boot process.
        entropy-generator = {
          enable = true;
          script = ''
            # Resolve the host device for the entropy source.
            HOST_ENTROPY_DEV="${pkgs.util-linux-minimal}/bin/randomctl"

            # Wait for the entropy device to be available.
            while ! "$HOST_ENTROPY_DEV" list 2>/dev/null; do
              sleep 0.1
            done

            # Seed the entropy pool with the host entropy.
            if "$HOST_ENTROPY_DEV" list 2>/dev/null | grep -q "Entropy available"; then
              "$HOST_ENTROPY_DEV" import \${config.nixos.tpm.rngDevice} 2>/dev/null || true
            fi
          '';
        };

        # Automatically grow the rootfs partition on boot.
        growfs = {
          enable = true;
          device = "/dev/vda3";
          mountpoint = "/";
          startBefore = ["local-fs.target"];
        };

        # A no-op service that triggers the /etc/machine-info file generation.
        # TODO: evaluate if config file should be generated by a different module
        machine-info-generator = {
          enable = true;
          after = ["network.target"];
          script = ''
            install -m 0644 /dev/null /etc/machine-info
            printf "PRETTY_HOSTNAME=%s\\n" "${config.networking.hostName}" > /etc/machine-info
          '';
        };

        # Use the TPM-based RNG from the host to seed the kernel entropy pool.
        rng-seed = {
          enable = true;
          after = ["entropy-generator.service"];
          wants = ["entropy-generator.service"];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStart = [
              "${pkgs.cryptsetup}/bin/cryptsetup"
              "luksOpen"
              "--type"
              "luks2"
              "${config.disks.luks.name}"
              "luks"
              "--key-file"
              "/dev/null"
              "--header"
              "/mnt/host/luks-header"
              "--disable-locks"
            ];
            ExecStop = [
              "${pkgs.cryptsetup}/bin/cryptsetup"
              "luksClose"
              "luks"
              "--disable-locks"
            ];
          };
        };

        # Automatically setup kernel modules on boot.
        kernel-module-loader = {
          enable = true;
          script = ''
            # Load KVM modules with Intel VT-x acceleration if available.
            if [ -d /sys/module/kvm_intel ]; then
              modprobe kvm_intel
            fi

            # Load KVM modules with AMD-V acceleration if available.
            if [ -d /sys/module/kvm_amd ]; then
              modprobe kvm_amd
            fi

            # Load virtio kernel modules for device virtualization.
            modprobe virtio_pci
            modprobe virtio_net
            modprobe virtio_balloon
            modprobe virtio_blk
            modprobe virtio_rng
            modprobe virtio_console

            # Load NVIDIA kernel modules if available.
            if lsmod 2>/dev/null | grep -q "^nvidia "; then
              modprobe nvidia_uvm
              modprobe nvidia_drm
              modprobe nvidia_modeset
            fi
          '';
        };

        # Automatically setup kernel modules on shutdown.
        kernel-module-cleanup = {
          enable = true;
          script = ''
            # Unload NVIDIA kernel modules if available.
            if lsmod 2>/dev/null | grep -q "^nvidia "; then
              modprobe -r nvidia_modeset
              modprobe -r nvidia_drm
              modprobe -r nvidia_uvm
              modprobe -r nvidia
            fi

            # Unload virtio kernel modules.
            modprobe -r virtio_pci
            modprobe -r virtio_net
            modprobe -r virtio_balloon
            modprobe -r virtio_blk
            modprobe -r virtio_rng
            modprobe -r virtio_console

            # Unload KVM modules.
            modprobe -r kvm_intel
            modprobe -r kvm_amd
            modprobe -r kvm
          '';
          before = ["shutdown.target"];
        };

        # Use timesyncd for automatic NTP synchronization on boot.
        timesyncd = {
          enable = true;
          settings = {
            "Time".NTP = [
              "pool.ntp.org"
            ];
          };
        };
      };

      # Netdata agent (non-GPU VMs)
      systemd.services.netdata = {
        after = [
          "network.target"
        ];
        wantedBy = ["multi-user.target"];
      };

      # Netdata agent (GPU VMs)
      systemd.services.netdata-gpu = {
        after = [
          "network.target"
        ];
        wantedBy = ["multi-user.target"];
      };
    };

    # Enable USB drivers in the containerdisk image.
    extrakernelPackages = [
      pkgs.usbutils
    ];

    # Enable USB device support in the containerdisk image.
    extrakernelModules = [
      "usb"
      "usbhid"
      "usb_storage"
      "uvcvideo"
    ];

    # Enable TPM and entropy pool in the containerdisk image.
    extraPackages = [
      pkgs.cryptsetup
      pkgs.tpm2-tools
      pkgs.tpm2-abrmd
      pkgs.tpm2-pytss
      pkgs.tpm2-tools-libtss-unwrapped
    ];
  };

  openssh = {
    enable = true;
    ports = [2222];
    settings = {
      "PubkeyAuthentication" = "yes";
      "PasswordAuthentication" = "no";
      "KbdInteractiveAuthentication" = "no";
      "PermitRootLogin" = "prohibit-password";
      "X11Forwarding" = "yes";
      "AllowTcpForwarding" = "yes";
      "PermitTunnel" = "yes";
      "ClientAliveInterval" = "0";
      "ClientAliveCountMax" = "3";
      "MaxSessions" = "100";
      "MaxStartups" = "100:30:100";
    };
  };

  users.users.admin = {
    name = "admin";
    description = "Machine administrator";
    isNormalUser = true;
    passwordFile = "/dev/null";
    homeDirectory = "/var/lib/admin";
    shell = "/run/current-system/sw/bin/fish";
    extraGroups = [
      "docker"
      "sudo"
      "input"
      "disk"
      "kvm"
      "render"
      "video"
    ];
  };

  # DO NOT EDIT BELOW — Machine type support.

  networking = {
    hostName = "catbox";
    inherit interfaces wireless regulatoryDomain;
    useDnsmasq = true;
    usePredictableInterfaceNames = true;
    firewall.enable = true;

    # Allow SSH from the tailnet.
    firewall.allowedTCPPorts = [
      2222
    ];

    # Allow ICMP ping and HTTP(S) from the tailnet.
    firewall.allowedUDPPorts = [
      "any"
    ];

    nftables = {
      # Allow SSH from the tailnet.
      extraRuleset = ''
        add inet filter input { type filter hook input priority 0; policy drop; }
        add inet filter input ct state established,related accept
        add inet filter input iif lo accept
        add inet filter input tcp dport { ssh, http, https } accept
        add inet filter input udp dport { 51820, 51820-60000 } accept
        add inet filter input ip6 nexthdr espv3 accept
        add inet filter input ip6 nexthdr icmpv6 accept
        add inet filter output ct state established,related accept
        add inet filter output iif lo accept
        add inet filter forward ct state established,related accept
        flush ruleset
      '';
    };

    # Tailnet configuration via Tailscale.
    tailscale.enable = true;
    tailscale.extraArgs = [
      "--advertise-tags=tag:k8s"
    ];
    tailscale.useRouting = false;
    tailscale.acceptDns = true;
    tailscale.dns = {
      nameservers = [
        "100.64.0.1"
      ];
    };

    # Prevent SSH timeouts by keeping the connection alive.
    extraNetworkingOptions = ''
      ServerAliveInterval 60
      ServerAliveCountMax 3
    '';
  };

  systemd.services.tailscale-operator = {
    description = "Tailscale Kubernetes Operator";
    after = ["network-online.target"];
    wantedBy = ["multi-user.target"];
    serviceConfig = {
      ExecStart = [
        "${pkgs.tailscale}/bin/tailscaled"
        "--socks5-server=localhost:1080"
        "--outbound-addr=100.64.0.12"
      ];
      Restart = "always";
    };
  };

  networking.firewall.allowedTCPPorts = [
    2222
  ];

  nixos-rebuild = {
    useChangePath = true;
    installInterval = 300;
    # Nixos-rebuild should not start nixos-rebuild.timer on machines.
    enable = false;
  };

  # DO NOT EDIT ABOVE — Machine type support.
}